// src/server/actions/dashboard.ts
"use server";

import { db } from "@/lib/db";
import { getUsage, isProUser } from "@/server/services/usage";
import { FREE_PLAN_MONTHLY_GENERATIONS } from "@/lib/constants/plans";
import { getRecentActivity } from "@/server/services/activity-log";
import { buildTodaysSuggestions } from "@/server/services/ai/suggestion-engine";

export async function getDashboardData(userId: string) {
  const brand = await db.brand.findFirst({
    where: { userId },
  });

  const [
    latestReport,
    previousReport,
    usage,
    isPro,
    activity,
    channelsCount,
    savedContentCount,
    queuedPosts,
    recentPosters,
  ] = await Promise.all([
    brand
      ? db.brandReport.findFirst({
          where: { brandId: brand.id },
          orderBy: { createdAt: "desc" },
        })
      : null,

    brand
      ? db.brandReport.findMany({
          where: { brandId: brand.id },
          orderBy: { createdAt: "desc" },
          skip: 1,
          take: 1,
        })
      : [],

    getUsage(userId),

    isProUser(userId),

    // Only two activities for dashboard preview
    getRecentActivity(userId, 2),

    db.channel.count({
      where: { userId },
    }),

    db.generatedContent.count({
      where: { userId },
    }),

    db.generatedContent.findMany({
      where: {
        userId,
        scheduledPosts: {
          none: {},
        },
      },
      orderBy: {
        createdAt: "desc",
      },
      take: 5,
      // FIX: this include was missing, which is what caused
      // item.posters to be undefined in ContentQueue and crash on [0].
      include: {
        posters: {
          select: {
            id: true,
            headline: true,
            backgroundUrl: true,
            finalUrl: true,
            visualStyle: true,
          },
        },
      },
    }),

    // Real visual work generated by the user
    db.poster.findMany({
      where: {
        userId,
        status: "READY",
      },
      orderBy: {
        createdAt: "desc",
      },
      take: 3,
      select: {
        id: true,
        headline: true,
        finalUrl: true,
        backgroundUrl: true,
        createdAt: true,
        recommendedPlatform: true,
      },
    }),
  ]);

  const scoreDelta =
    latestReport && previousReport[0]
      ? latestReport.score - previousReport[0].score
      : null;

  return {
    brandName: brand?.brandName ?? null,

    usage,
    isPro,
    usageLimit: FREE_PLAN_MONTHLY_GENERATIONS,

    channelsCount,
    savedContentCount,

    brandScore: latestReport?.score ?? null,
    brandScoreDelta: scoreDelta,

    suggestions: buildTodaysSuggestions(latestReport),

    queuedPosts,

    // Dashboard preview
    activity,

    // Real generated visual work
    recentPosters,
  };
}